package org.gameleira.statesBrazilians.model;

/**
 * ENUM QUE REPRESENTA OS ESTADOS BRASILEIROS.
 *
 * UM ENUM (ENUMERAÇÃO) É UM TIPO DE DADO ESPECIAL EM JAVA QUE REPRESENTA UM CONJUNTO FIXO DE CONSTANTES.
 * NESTE CASO, ELE REPRESENTA DIFERENTES ESTADOS BRASILEIROS.
 *
 * CADA CONSTANTE DECLARADA NO ENUM É UMA INSTÂNCIA DO PRÓPRIO TIPO ENUM. NESSE EXEMPLO, OS ESTADOS SÃO
 * DEFINIDOS COMO CONSTANTES, CADA UM ASSOCIADO A UM ATRIBUTO STRING QUE REPRESENTA O SEU NOME COMPLETO
 *
 * OS ENUMS PODEM CONTER ATRIBUTOS, MÉTODOS E CONSTRUTORES PRIVADOS. TODAS AS INSTÂNCIAS DO ENUM SÃO IMUTÁVEIS
 *
 * A ESTRUTURA DESTE ENUM INCLUI:
 * 
 *   DUAS CONSTANTES REPRESENTANDO OS ESTADOS: {@code SAO_PAULO} E {@code RIO_DE_JANEIRO}.
 *   UM ATRIBUTO {@code NAME} PARA ARMAZENAR O NOME COMPLETO DO ESTADO.
 *   UM CONSTRUTOR PRIVADO QUE ATRIBUI O NOME AO ATRIBUTO {@code NAME}.
 *   UM MÉTODO {@code GETNAME()} PARA RETORNAR O VALOR DO ATRIBUTO {@code NAME}.
 * 
 */
public enum StateBrazilian {
    
    /** INSTÂNCIA DO ENUM REPRESENTANDO O ESTADO DE SÃO PAULO */
    SAO_PAULO("SÃO PAULO"),
    
    /** INSTÂNCIA DO ENUM REPRESENTANDO O ESTADO DO RIO DE JANEIRO */
    RIO_DE_JANEIRO("RIO DE JANEIRO");
    
    /** ATRIBUTO QUE ARMAZENA O NOME COMPLETO DO ESTADO */
    private final String name;
    
    /**
     * CONSTRUTOR PRIVADO DO ENUM.
     *
     * OS ENUMS NÃO PODEM TER CONSTRUTORES PÚBLICOS, POIS SUAS INSTÂNCIAS SÃO DEFINIDAS ESTATICAMENTE.
     * O CONSTRUTOR É CHAMADO AUTOMATICAMENTE NO MOMENTO DA INICIALIZAÇÃO.
     */
    private StateBrazilian(String name) {
        this.name = name;
    }

    /**
     * MÉTODO PARA OBTENÇÃO DO NOME DO ESTADO.
     *
     * COMO OS ATRIBUTOS DE ENUM SÃO PRIVADOS, ESTE MÉTODO FORNECE ACESSO AO VALOR DO ATRIBUTO {@code NAME}.
     */
    public String getName() {
        return name;
    }
}
